import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import styles from "./layout.module.css";
import Sidebar from "./components/Sidebar";
import TopBar from "./components/TopBar";
import { ModalProvider } from "./context/ModalContext";
import GlobalModal from "./components/GlobalModal";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ModalProvider>
          <div className={styles.layoutContainer}>
            <Sidebar />
            <main className={styles.mainContent}>
              <TopBar />
              {children}
            </main>
          </div>
          <GlobalModal />
        </ModalProvider>
      </body>
    </html>
  );
}
